common:
  fps: 25
  image_size: 256
  hidden_size: 50
  embedding_dim: 384

dataset:
  base_dir: datasets
  videos_dir: datasets/videos
  audios_dir: datasets/audios
  images_dir: datasets/images
  latents_dir: datasets/latents
  audio_window: 0

train:
  batch_size: 4
  epochs: 10
  audio_window: 0
  related_window: 5
  gamma: 0.5
  output: outputs/checkpoints

avatar:
  avatar_dir: results

models:
  whisper_path: models/whisper/tiny.pt
  whisper_fine_tuning_path: models/whisper-tiny-zh
  unet_path: models/musetalk
  vae_path: models/sd-vae-ft-mse
  dwpose_config_path: models/dwpose/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py
  dwpose_model_path: models/dwpose/dw-ll_ucoco_384.pth
